### ISSUE TITLE
Plugin Waiting Too Long to Request Alert Permission

### ISSUE THREAD

**Issue by YoungJM** [ibm-bluemix-mobile-services/bms-clientsdk-cordova-plugin-push#12]
When running the hellopush cordova sample (and likely any application using this plugin) the application does not prompt the user to allow push notifications until it reaches the first line in the function `hasPushEnabled()` in CDVMFPPush.swift which is being used to check whether the user has allowed Push Notifications. The plugin then does not wait for the user response and immediately returns false which results in the PluginResult to show an error with the message "The notification was blocked by user". This will be shown before the user has time to respond to the alert permission prompt and will occur on first install every time.

**Comment by mjparangot** [comment]
I removed the code that blocks the notification. Should be working now

**Comment by AnanthaKrish** [comment]
Fixed

**Comment by jmereaux** [comment]
Still facing the issue with ibm-mfp-push@1.0.13. Any solution please?
